baseUrl=https://www.zigwheels.com/
moreBtn.xpath=//*[@id="headerNewVNavWrap"]/nav/ul/li[5]
usedCars.xpath=//a[@title='Used Cars']
usedCars.url=https://www.zigwheels.com/used-car

upcomingBikes.url=https://www.zigwheels.com/
chennai.usedCars.xpath=//*[@id="popularCityList"]/li[7]/a
popularModels.xpath=//ul[contains(@class,'popularModels')]//label



implicitWait=10